package cn.jxhun.pojo;

import cn.jxhun.pojo.Ikecheng;

public interface IkechengMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ikecheng
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ikecheng
     *
     * @mbg.generated
     */
    int insert(Ikecheng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ikecheng
     *
     * @mbg.generated
     */
    int insertSelective(Ikecheng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ikecheng
     *
     * @mbg.generated
     */
    Ikecheng selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ikecheng
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Ikecheng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ikecheng
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ikecheng record);
}