package cn.jxhun.pojo;

public class Ikecheng {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ikecheng.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ikecheng.kname
     *
     * @mbg.generated
     */
    private String kname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ikecheng.chengji
     *
     * @mbg.generated
     */
    private Integer chengji;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ikecheng.s_id
     *
     * @mbg.generated
     */
    private Integer sId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ikecheng.id
     *
     * @return the value of ikecheng.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ikecheng.id
     *
     * @param id the value for ikecheng.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ikecheng.kname
     *
     * @return the value of ikecheng.kname
     *
     * @mbg.generated
     */
    public String getKname() {
        return kname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ikecheng.kname
     *
     * @param kname the value for ikecheng.kname
     *
     * @mbg.generated
     */
    public void setKname(String kname) {
        this.kname = kname == null ? null : kname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ikecheng.chengji
     *
     * @return the value of ikecheng.chengji
     *
     * @mbg.generated
     */
    public Integer getChengji() {
        return chengji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ikecheng.chengji
     *
     * @param chengji the value for ikecheng.chengji
     *
     * @mbg.generated
     */
    public void setChengji(Integer chengji) {
        this.chengji = chengji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ikecheng.s_id
     *
     * @return the value of ikecheng.s_id
     *
     * @mbg.generated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ikecheng.s_id
     *
     * @param sId the value for ikecheng.s_id
     *
     * @mbg.generated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }
}