package cn.jxhun.pojo;

public class Iren {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iren.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iren.xingming
     *
     * @mbg.generated
     */
    private String xingming;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iren.s_id
     *
     * @mbg.generated
     */
    private Integer sId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iren.id
     *
     * @return the value of iren.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iren.id
     *
     * @param id the value for iren.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iren.xingming
     *
     * @return the value of iren.xingming
     *
     * @mbg.generated
     */
    public String getXingming() {
        return xingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iren.xingming
     *
     * @param xingming the value for iren.xingming
     *
     * @mbg.generated
     */
    public void setXingming(String xingming) {
        this.xingming = xingming == null ? null : xingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iren.s_id
     *
     * @return the value of iren.s_id
     *
     * @mbg.generated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iren.s_id
     *
     * @param sId the value for iren.s_id
     *
     * @mbg.generated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }
}